blank_issues_enabled: false
contact_links:
  - name: Ask a question / usage discussion
    url: https://github.com/allamiro/ansible-controller/discussions
    about: Use Discussions for open-ended questions or how-to help
